language: python
dist: xenial
sudo: false
cache:
  pip: true
branches:
  only:
  - master
  # Tags
  - /^(\d+\.)+\d+(\.\S+)?$/

matrix:
  fast_finish: true
  include:
    - python: '3.5'
    - python: '3.7'
    - python: '3.8'
      name: 'Lint, Coverage'
      before_script:
        - pip install flake8 coverage mypy pandoc
      script:
        - find -name '*.md' | xargs .github/lint-markdown.sh
        - flake8
        - mypy pdoc
        - time catchsegv coverage run setup.py test
        - PDOC_TEST_PANDOC=1 python -m unittest pdoc.test.CliTest.test_pdf_pandoc
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - python: '3.8'
      name: 'Docs'
      stage: deploy
      script:
        - doc/build.sh
      after_success:
        - if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then bash .github/deploy-gh-pages.sh; fi

before_install:
  - set -e

install:
  - pip install .

script:
  - catchsegv python setup.py test
